M48
; DRILL file {KiCad 7.0.10} date Tue Feb 13 14:16:55 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-13T14:16:55+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.42Y-2.1
X3.42Y-4.58
X5.52Y-3.26
X6.57Y-2.13
X6.57Y-2.86
X6.63Y-4.17
M30
